"""
Django settings for api_topicos project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
from pathlib import Path

from api_rest.logging_utils import ensure_logs_dir

BASE_DIR = Path(__file__).resolve().parent.parent
LOGS_DIR = ensure_logs_dir(BASE_DIR)

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-key-change-in-production')
DEBUG = os.environ.get('DEBUG', 'True') == 'True'
APP_VERSION = "0.1.0-dev"
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'health_check',
    'channels',
    'api_rest',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'api_rest.middleware.CorrelationIdMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api_topicos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api_topicos.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.environ.get('DB_NAME', 'api_topicos_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres123'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8080',
    'http://localhost:3000',
]
CORS_ALLOW_ALL_ORIGINS = True

SIMPLE_JWT = {
    'USER_ID_FIELD': 'user_nickname',
    'USER_ID_CLAIM': 'user_nickname',
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api_rest.authentication.JWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.openapi.AutoSchema',
}

RABBITMQ = {
    'HOST': os.environ.get('RABBITMQ_HOST', 'rabbitmq'),
    'PORT': int(os.environ.get('RABBITMQ_PORT', '5672')),
    'USER': os.environ.get('RABBITMQ_USER', 'guest'),
    'PASSWORD': os.environ.get('RABBITMQ_PASSWORD', 'guest'),
    'ORDER_CREATED_EXCHANGE': os.environ.get('RABBITMQ_ORDER_CREATED_EXCHANGE', 'orders'),
    'ORDER_CREATED_ROUTING_KEY': os.environ.get('RABBITMQ_ORDER_CREATED_ROUTING_KEY', 'order.created'),
    'ORDER_CREATED_QUEUE': os.environ.get('RABBITMQ_ORDER_CREATED_QUEUE', 'order.created.notifications'),
}

REDIS = {
    'HOST': os.environ.get('REDIS_HOST', 'localhost'),
    'PORT': int(os.environ.get('REDIS_PORT', '6379')),
    'DB': int(os.environ.get('REDIS_DB', '0')),
    'PASSWORD': os.environ.get('REDIS_PASSWORD', 'redissenha123'),
    'KEY_PREFIX': os.environ.get('REDIS_KEY_PREFIX', 'api_topicos:'),
    'ITEM_TTL_SECONDS': int(os.environ.get('REDIS_ITEM_TTL_SECONDS', '300')),
    'LIST_TTL_SECONDS': int(os.environ.get('REDIS_LIST_TTL_SECONDS', '120')),
}

REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', '')
REDIS_AUTH_PART = f":{REDIS_PASSWORD}@" if REDIS_PASSWORD else ''
REDIS_CHANNEL_URL = (
    f"redis://{REDIS_AUTH_PART}{os.environ.get('REDIS_HOST', '127.0.0.1')}:{os.environ.get('REDIS_PORT', '6379')}/0"
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'correlation_id': {
            '()': 'api_rest.logging_utils.CorrelationIdFilter',
        },
    },
    'formatters': {
        'json': {
            '()': 'api_rest.logging_utils.StructuredJsonFormatter',
            'fmt': '%(asctime)s %(levelname)s %(name)s %(message)s %(correlation_id)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
            'filters': ['correlation_id'],
        },
        'file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(LOGS_DIR / 'api.log'),
            'when': 'midnight',
            'backupCount': 7,
            'encoding': 'utf-8',
            'formatter': 'json',
            'filters': ['correlation_id'],
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'api.request': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'api_rest.notifications': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'api_rest.rabbitmq': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'api_rest.management.commands.consume_order_created': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

ASGI_APPLICATION = 'api_topicos.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_CHANNEL_URL],
        },
    },
}

CELERY_BROKER_URL = os.environ.get(
    'CELERY_BROKER_URL',
    f"redis://{REDIS_AUTH_PART}{os.environ.get('REDIS_HOST', 'redis')}:{os.environ.get('REDIS_PORT', '6379')}/0",
)
CELERY_RESULT_BACKEND = os.environ.get(
    'CELERY_RESULT_BACKEND',
    CELERY_BROKER_URL,
)
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'False') == 'True'
CELERY_TASK_EAGER_PROPAGATES = True
