sonar.projectKey=augustoluizdev_projetotopicosavancados
sonar.organization=augustoluizdev
sonar.projectName=projetotopicosavancados
sonar.projectVersion=1.0

sonar.sources=api_rest,api_topicos
sonar.tests=api_rest
sonar.test.inclusions=api_rest/tests.py,api_rest/tests/**/*.py

sonar.exclusions=**/__pycache__/**,**/migrations/**,**/staticfiles/**,**/venv/**,**/logs/**
sonar.coverage.exclusions=api_rest/tests.py,api_rest/tests/**/*.py,api_topicos/asgi.py,api_topicos/wsgi.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
